// Extensions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

private func encodeIfPossible<T: Sendable>(_ object: T, codableHelper: CodableHelper) -> any Sendable {
    if let data = object as? Data {
        return data.base64EncodedString(options: Data.Base64EncodingOptions())
    } else if let date = object as? Date {
        return codableHelper.dateFormatter.string(from: date)
    } else if let uuid = object as? UUID {
        return "\(uuid)"
    } else if let item = object as? any RawRepresentable {
        return encodeIfPossible(item.rawValue as! any Sendable, codableHelper: codableHelper)
    } else {
        return object
    }
}

extension Array where Element: Sendable {
    func encodeToJSON(codableHelper: CodableHelper) -> any Sendable {
        return self.map { encodeIfPossible($0, codableHelper: codableHelper) }
    }
}

extension Set where Element: Sendable {
    func encodeToJSON(codableHelper: CodableHelper) -> any Sendable {
        return Array(self).encodeToJSON(codableHelper: codableHelper)
    }
}

extension Dictionary where Key: Sendable, Value: Sendable {
    func encodeToJSON(codableHelper: CodableHelper) -> any Sendable {
        var dictionary = [Key: any Sendable]()
        for (key, value) in self {
            dictionary[key] = encodeIfPossible(value, codableHelper: codableHelper)
        }
        return dictionary
    }
}

